api_platform:
  title: 'StyleStock API'
  description: 'API used for StyleStock project'
  version: '1.0.0'

  formats:
    jsonld: ['application/ld+json']
    json: ['application/json']
    html: ['text/html']
    multipart: ['multipart/form-data']

  collection:
    order: 'DESC'
    order_parameter_name: 'order'
    pagination:
      enabled: true
      page_parameter_name: page
      items_per_page_parameter_name: limit

  defaults:
    pagination_client_items_per_page: true  

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header

  show_webby: false

  eager_loading:
    enabled: true
    max_joins: 3000
    fetch_partial: true

  
    