vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        image:
           uri_prefix: /image
           upload_destination: '%kernel.project_dir%/public/images'
           namer: Vich\UploaderBundle\Naming\OrignameNamer
